name: Azure Resources Pipelines

on:
  workflow_dispatch:
  
jobs:
  deploy-resources:
    runs-on: ubuntu-latest
    env:
      VAULT_NAME: npvaulttechnews
    steps:
    - name: Clone Repo
      uses: actions/checkout@v3

    - name: Azure Login
      id: login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Deploy Container Registry
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: 5d17a1d6-e7cf-4fb4-978f-701807e9dd06
        resourceGroupName: rg-tech-challenge-02
        template: ./azure/arm-templates/resource/acr-template.json
        parameters: ./azure/arm-templates/resource/parameters.json

    - name: Set ACR Anonymous Pull
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          az acr update --name acrtechnews --anonymous-pull-enabled true

    - name: Deploy Key Vault
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: 5d17a1d6-e7cf-4fb4-978f-701807e9dd06
        resourceGroupName: rg-tech-challenge-02
        template: ./azure/arm-templates/resource/key-vault-template.json
        parameters: ./azure/arm-templates/resource/parameters.json

    - name: Upload Vault Secrets
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          az keyvault secret set --vault-name $VAULT_NAME --name administratorLogin --value ${{secrets.ADMIN_LOGIN}}
          az keyvault secret set --vault-name $VAULT_NAME --name administratorLoginPassword --value ${{secrets.ADMIN_PASSWORD}}
          az keyvault secret set --vault-name $VAULT_NAME --name clientIpValue --value ${{secrets.CLIENT_IP}}

    - name: Deploy Blob Storage
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: 5d17a1d6-e7cf-4fb4-978f-701807e9dd06
        resourceGroupName: rg-tech-challenge-02
        template: ./azure/arm-templates/resource/storage-template.json
        parameters: ./azure/arm-templates/resource/parameters.json

    - name: Deploy TechNewsAuth Database Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: 5d17a1d6-e7cf-4fb4-978f-701807e9dd06
        resourceGroupName: rg-tech-challenge-02
        template: ./azure/arm-templates/database/template.json
        parameters: ./azure/arm-templates/database/parameters-TechNewsAuth.json

    - name: Deploy TechNews Database Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: 5d17a1d6-e7cf-4fb4-978f-701807e9dd06
        resourceGroupName: rg-tech-challenge-02
        template: ./azure/arm-templates/database/template.json
        parameters: ./azure/arm-templates/database/parameters-TechNews.json