name: Azure Resources Pipelines

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  deploy-resources:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      id: login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
      
    - name: Deploy ARM Template
      uses: azure/cli@v1
      with:
          azcliversion: latest
          inlineScript: |
            az deployment group create --resource-group tech-challenge-02 --template-file ./azure/resource/template.json --parameters ./azure/resource/parameters.json
  
  deploy-auth-database:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      id: login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
      
    - name: Deploy ARM Template
      uses: azure/cli@v1
      with:
          azcliversion: latest
          inlineScript: |
            az deployment group create --resource-group tech-challenge-02 --template-file ./azure/database/template.json --parameters ./azure/database/parameters-TechNewsAuth.json
  
  deploy-core-database:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      id: login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
      
    - name: Deploy ARM Template
      uses: azure/cli@v1
      with:
          azcliversion: latest
          inlineScript: |
            az deployment group create --resource-group tech-challenge-02 --template-file ./azure/database/template.json --parameters ./azure/database/parameters-TechNews.json