name: Build Pipelines

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build-apps:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore Dependencies
      run: dotnet restore
      
    - name: Build Apps
      run: dotnet build --no-restore
  
  push-auth-image:
    runs-on: ubuntu-latest
    needs: [build-apps] 
    steps:
    - name: Clone Repo
      uses: actions/checkout@v3.5.3
    
    - name: Azure Login
      id: login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Push TechNews Auth API
      uses: azure/cli@v1
      with:
        max_attempts: 1
        retry_on: error
        azcliversion: latest
        inlineScript: |
            az acr build --image technews-auth-api:v1 --registry acrtechnews --file ./src/api/TechNews.Auth.Api/Dockerfile .
  
  push-core-image:
    runs-on: ubuntu-latest
    needs: [build-apps]
    steps:
    - name: Clone Repo
      uses: actions/checkout@v3.5.3
    
    - name: Azure Login
      id: login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
    - name: Push TechNews Core API
      uses: azure/cli@v1
      with:
          max_attempts: 1
          retry_on: error
          azcliversion: latest
          inlineScript: |
            az acr build --image technews-core-api:v1 --registry acrtechnews --file ./src/api/TechNews.Core.Api/Dockerfile .

  push-web-image:
    runs-on: ubuntu-latest
    needs: [build-apps]
    steps:
    - name: Clone Repo
      uses: actions/checkout@v3.5.3

    - name: Azure Login
      id: login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
    - name: Push TechNews Web
      uses: azure/cli@v1
      with:
          max_attempts: 1
          retry_on: error
          azcliversion: latest
          inlineScript: |
            az acr build --image technews-web:v1 --registry acrtechnews --file ./src/web/TechNews.Web/Dockerfile .
