name: .NET

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  
  
  push-images:
    runs-on: ubuntu-latest
    #needs: [build-apps]
    steps:
    #- name: Obtendo o código fonte
    #  uses: actions/checkout@v3.5.3
    
    - name: Azure Login
      id: login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Push TechNews Auth API
      uses: azure/cli@v1
      with:
          azcliversion: latest
          inlineScript: |
            az acr build --image technews-auth-api:v1 --registry techchallenge02 --file ./src/api/TechNews.Auth.Api/Dockerfile .
