name: .NET

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build-apps:
    runs-on: ubuntu-latest
    steps:
    - name: Cloning repo
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
  
  build-images:
    runs-on: ubuntu-latest
    needs: [build-apps]
    steps:
    #- name: Obtendo o código fonte
    #  uses: actions/checkout@v3.5.3
    
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - run: |
        az account show
        az group list
    
