name: Deploy Pipelines

on:
  workflow_dispatch:

jobs:
  deploy-auth-container:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      id: login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Deploy TechNews Auth Container
      uses: azure/cli@v1
      with:
          max_attempts: 1
          retry_on: error
          azcliversion: latest
          inlineScript: |
            az container create \
            --resource-group rg-tech-challenge-02 \
            --assign-identity \
            --environment-variables \
            TECHNEWS_AUTH_API_DATABASE_CONNECTION_STRING="Server=tcp:dbstechnews.database.windows.net,1433;Initial Catalog=TechNewsAuth;Persist Security Info=False;User ID=${{ secrets.DATABASE_USERNAME }};Password=${{ secrets.DATABASE_PASSWORD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;pooling=true" \
            AZURE_KEY_VAULT_URL="https://npvaulttechnews.vault.azure.net/" \
            ASPNETCORE_URLS="http://+:5138" \
            TOKEN_EXPIRATION_IN_MINUTES="${{ vars.TOKEN_EXPIRATION_IN_MINUTES }}" \
            KEY_ROTATOR_EXECUTION_IN_MINUTES="${{ vars.KEY_ROTATOR_EXECUTION_IN_MINUTES }}" \
            KEY_CREATION_SIZE_IN_BITS="${{ vars.KEY_CREATION_SIZE_IN_BITS }}" \
            KEY_EXPIRATION_IN_DAYS="${{ vars.KEY_EXPIRATION_IN_DAYS }}" \
            CRYPTOGRAPHIC_ALGORITHM="${{ vars.CRYPTOGRAPHIC_ALGORITHM }}" \
            --memory 0.5 --cpu 1 --ports 5138 \
            --ip-address Public \
            --dns-name-label technews-auth-api \
            --registry-login-server acrtechnews.azurecr.io \
            --registry-username "anonymous" \
            --registry-password "anonymous" \
            --name technews-auth-api-container \
            --image acrtechnews.azurecr.io/technews-auth-api:v1
    
    - name: Grant Access to Key Vault
      uses: azure/cli@v1
      with:
          max_attempts: 1
          retry_on: error
          azcliversion: latest
          inlineScript: |
            response=$(az container show \
            --resource-group rg-tech-challenge-02 \
            --name technews-auth-api-container \
            --query identity --output json)

            assignee_object_id=$(echo "$response" | jq -r '.principalId')

            az role assignment create \
            --role "Key Vault Administrator" \
            --assignee-principal-type ServicePrincipal \
            --assignee-object-id "$assignee_object_id" \
            --scope /subscriptions/5d17a1d6-e7cf-4fb4-978f-701807e9dd06/resourceGroups/rg-tech-challenge-02/providers/Microsoft.KeyVault/vaults/npvaulttechnews

    - name: Restart Container
      uses: azure/cli@v1
      with:
          max_attempts: 1
          retry_on: error
          azcliversion: latest
          inlineScript: |
            az container restart --name technews-auth-api-container  --resource-group rg-tech-challenge-02

    - name: Health Check Auth
      run: |
        RESPONSE=$(curl -s "http://technews-auth-api.brazilsouth.azurecontainer.io:5138/health")

        if [[ "$RESPONSE" == *"Healthy"* ]]; then
          echo "API is Healthy"
        else
          echo "API is not Healthy"
          exit 1
        fi

  deploy-core-container:
    runs-on: ubuntu-latest
    needs: [deploy-auth-container]
    steps:
    - name: Azure Login
      id: login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
    - name: Deploy TechNews Core Container
      uses: azure/cli@v1
      with:
          max_attempts: 1
          retry_on: error
          azcliversion: latest
          inlineScript: |
            az container create \
            --resource-group rg-tech-challenge-02 \
            --environment-variables \
            TECHNEWS_CORE_API_DATABASE_CONNECTION_STRING="Server=tcp:dbstechnews.database.windows.net,1433;Initial Catalog=TechNews;Persist Security Info=False;User ID=${{ secrets.DATABASE_USERNAME }};Password=${{ secrets.DATABASE_PASSWORD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;pooling=true" \
            ASPNETCORE_URLS="http://+:5142" \
            TECHNEWS_CORE_API_AUTH_JWKS_URL="http://technews-auth-api.brazilsouth.azurecontainer.io:5138/jwks" \
            --memory 0.5 --cpu 1 --ports 5142 \
            --ip-address Public \
            --dns-name-label technews-core-api \
            --registry-login-server acrtechnews.azurecr.io \
            --registry-username "anonymous" \
            --registry-password "anonymous" \
            --name technews-core-api-container \
            --image acrtechnews.azurecr.io/technews-core-api:v1

    - name: Health Check Core
      run: |
        RESPONSE=$(curl -s "http://technews-core-api.brazilsouth.azurecontainer.io:5142/health")

        if [[ "$RESPONSE" == *"Healthy"* ]]; then
          echo "API is Healthy"
        else
          echo "API is not Healthy"
          exit 1
        fi

  deploy-web-container:
    runs-on: ubuntu-latest
    needs: [deploy-auth-container, deploy-core-container]
    steps:
    - name: Azure Login
      id: login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
    - name: Deploy TechNews Web Container
      uses: azure/cli@v1
      with:
          max_attempts: 1
          retry_on: error
          azcliversion: latest
          inlineScript: |
            az container create \
            --resource-group rg-tech-challenge-02 \
            --environment-variables \
            TECHNEWS_APP_API_AUTH_URL="http://technews-auth-api.brazilsouth.azurecontainer.io:5138" \
            TECHNEWS_APP_API_CORE_URL="http://technews-core-api.brazilsouth.azurecontainer.io:7105" \
            ASPNETCORE_URLS="http://+:5055" \
            --memory 0.5 --cpu 1 --ports 5055 \
            --ip-address Public \
            --dns-name-label technews-web \
            --registry-login-server acrtechnews.azurecr.io \
            --registry-username "anonymous" \
            --registry-password "anonymous" \
            --name technews-web-container \
            --image acrtechnews.azurecr.io/technews-web:v1
