name: Deploy Pipelines

on:
  workflow_dispatch:
  
jobs:
  deploy-migrations:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v3

    - name: Azure Login
      id: login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Run Auth Migrations
      uses: azure/sql-action@v2.2
      with:        
        connection-string: 'Server=tcp:dbstechnews.database.windows.net,1433;Initial Catalog=TechNewsAuth;Persist Security Info=False;User ID=${{ secrets.DATABASE_USERNAME }};Password=${{ secrets.DATABASE_PASSWORD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;pooling=true'
        path: './azure/sql/auth/scripts/*.sql'

  deploy-auth-container:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      id: login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Deploy TechNews Auth Container
      uses: azure/cli@v1
      with:
          max_attempts: 1
          retry_on: error
          azcliversion: latest
          inlineScript: |
            az container create \
            --resource-group rg-tech-challenge-02 \
            --environment-variables \
            TECHNEWS_AUTH_API_DATABASE_CONNECTION_STRING="Server=tcp:dbstechnews.database.windows.net,1433;Initial Catalog=TechNewsAuth;Persist Security Info=False;User ID=${{ secrets.DATABASE_USERNAME }};Password=${{ secrets.DATABASE_PASSWORD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;pooling=true" \
            ASPNETCORE_URLS="http://+:5138" \
            TOKEN_EXPIRATION_IN_MINUTES="${{ vars.TOKEN_EXPIRATION_IN_MINUTES }}" \
            KEY_ROTATOR_EXECUTION_IN_MINUTES="${{ vars.KEY_ROTATOR_EXECUTION_IN_MINUTES }}" \
            KEY_CREATION_SIZE_IN_BITS="${{ vars.KEY_CREATION_SIZE_IN_BITS }}" \
            KEY_EXPIRATION_IN_DAYS="${{ vars.KEY_EXPIRATION_IN_DAYS }}" \
            CRYPTOGRAPHIC_ALGORITHM="${{ vars.CRYPTOGRAPHIC_ALGORITHM }}" \
            --memory 0.5 --cpu 1 --ports 5138 \
            --ip-address Public \
            --dns-name-label technews-auth-api \
            --registry-login-server acrtechnews.azurecr.io \
            --registry-username ${{ secrets.REGISTRY_USERNAME }} \
            --registry-password ${{ secrets.REGISTRY_PASSWORD }} \
            --name technews-auth-api-container \
            --image acrtechnews.azurecr.io/technews-auth-api:v1
    - name: Health Check Auth
      run: |
        RESPONSE=$(curl -s "http://technews-auth-api.brazilsouth.azurecontainer.io:5138/health")

        if [[ "$RESPONSE" == *"Healthy"* ]]; then
          echo "API is Healthy"
        else
          echo "API is not Healthy"
          exit 1
        fi
